[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "muninn_prototype"
version = "0.0.1"
description = "Python software prototype for the Delta Suit Spacesuit Simulator of the Austrian Space Forum"

readme = "README.md"

requires-python = ">=3.11"

authors = [
    { name = "Leon Krieger" }
]

dependencies = [
    "paho-mqtt>=2.0.0",
    "pypubsub>=4.0.0",
    "pyzmq>=26.0.0",
    "adafruit-blinka>=8.0.0",
    "gpiozero>=2.0.0",
    "adafruit-circuitpython-bme680>=2.0.0",
    "adafruit-circuitpython-emc2101",
    "sparkfun-qwiic-alphanumeric>=2.0.0",
    "picamera2>=0.3.24",
]

[project.scripts]
muninn = "muninn_prototype.main:main"
